# Generated by Django 5.2.6 on 2025-09-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('turf', models.CharField(max_length=100)),
                ('slot', models.CharField(max_length=50)),
                ('is_tournament', models.BooleanField()),
                ('tournament_name', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
