# Generated by Django 5.2.6 on 2025-09-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0003_booking_amount_booking_is_booked_booking_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='turfs/'),
        ),
        migrations.AddField(
            model_name='turf',
            name='location',
            field=models.CharField(default='Madurai', max_length=100),
        ),
    ]
