# Generated by Django 5.2.6 on 2025-09-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0005_book_remove_turf_image_remove_turf_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('turf_name', models.CharField(max_length=100)),
                ('turf_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('slot', models.CharField(max_length=50)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
