# Generated by Django 5.2.6 on 2025-09-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0006_quickbooking_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='QuickBooking',
        ),
    ]
