# Generated by Django 5.2.6 on 2025-09-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0007_quickmessage_delete_quickbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickmessage',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
